name: "Get and cache deps"
description: "Get the deps and cache them via NPM"
inputs:
  caching:
    description: "Should deps be cached or not"
    required: false
    default: "true"
outputs:
  cache-hit:
    description: "Whether the cache was hit or not"
    value: ${{steps.install}}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{inputs.caching}}'" >> $GITHUB_OUTPUT
      shell: bash
